StudioBriefcase/StudioBriefcase/ViewComponents/PageNavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StudioBriefcase.Models;
using StudioBriefcase.Services;

namespace StudioBriefcase.ViewComponents
{
    public class PageNavigationViewComponent : ViewComponent
    {
        PageService _pageService;

        public PageNavigationViewComponent(PageService pageService)
        {
            _pageService = pageService;
        }

        /// <summary>
        /// Queries the Database for the list of subjects and topics to populate the library navigation panel
        /// </summary>
        /// <param name="path"></param>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync(uint topicID, uint languageID)
        {

            SubLayoutNavigationModel listData = new SubLayoutNavigationModel(languageID);
            if(languageID == 0)
            {
                listData.Links = await _pageService.MakeSubLayoutNavigationLinksAsync(topicID);
            }
            else
            {
                listData = await _pageService.MakeSubLayoutNavigationLinksAsync(topicID, languageID);
            }

            

            return View("~/Pages/Shared/Components/Page/_Page_NavigationLinks.cshtml", listData);
        }
    }
}

StudioBriefcase/StudioBriefcase/ViewComponents/PageQuickLinksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StudioBriefcase.Services;

namespace StudioBriefcase.ViewComponents
{
    public class PageQuickLinksViewComponent : ViewComponent
    {
        PageService _pageService;

        public PageQuickLinksViewComponent(PageService pageService)
        {
            _pageService = pageService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string libraryName, int switchvalue = 0)
        {
            var modelList = await _pageService.GetLibraryQuickLinksAsync(libraryName);

            string view = string.Empty;

            switch (switchvalue)
            {
                case 0:
                    view = "~/Pages/Shared/Components/Page/_PageQuickLinks.cshtml";
                    break;
                case 1:
                    view = "~/Pages/Shared/Components/Custodian/_Custodian_PageQuickLinks.cshtml";
                    break;
            }

            return View(view, modelList);
        }

    }
}

StudioBriefcase/StudioBriefcase/ViewComponents/Page_MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StudioBriefcase.Services;
using StudioBriefcase.Models;

namespace StudioBriefcase.ViewComponents
{
    public class Page_MenuViewComponent : ViewComponent
    {
        PageService _pageService;
        public Page_MenuViewComponent(PageService pageService)
        {
            _pageService = pageService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            LanguageModel languages = new LanguageModel(0);
            languages.options = await _pageService.GetLanguages();
            
            return View("~/Pages/Shared/Components/Page/_Page_Menu.cshtml", languages);
        }

    }
}

StudioBriefcase/StudioBriefcase/ViewComponents/Page_TagsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StudioBriefcase.Services;
using StudioBriefcase.Models;

namespace StudioBriefcase.ViewComponents
{
    public class Page_TagsViewComponent : ViewComponent
    {

        PageService _pageService;

        public Page_TagsViewComponent(PageService pageService)
        {
            _pageService = pageService;
        }

        //[ResponseCache(Duration = 3600)] //Not Caching Response
        public async Task<IViewComponentResult> InvokeAsync()
        {
            TagsModel tags = new TagsModel();
            tags.TagLists = await _pageService.GetLibraryTagsAsync();

            return View("~/Pages/Shared/Components/Page/_Page_Navigation_Tags.cshtml", tags);
        }

    }
}

StudioBriefcase/StudioBriefcase/Pages/Shared/_Form_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @*Globally Used Styles for element flow and control*@
    <link rel="stylesheet" href="~/css/baseStyles.css" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

StudioBriefcase/StudioBriefcase/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @*Site Specific Styles and themes*@
    <link rel="stylesheet" href="~/css/site.css" />
    @*Globally Used Styles for element flow and control*@
    <link rel="stylesheet" href="~/css/baseStyles.css" />
    @* Redefinition of html Tags *@
    <link rel="stylesheet" href="~/css/themes.css" />
    @*Helper Styles to add visual Assistance to the development process*@
    <link rel="stylesheet" href="~/css/helperStyles.css" />

    @* Default Colors used in the website and altered values used in darkmode *@
    <partial name="_colors" />
    <link rel="stylesheet" href="~/css/ColorStyles.css" />

</head>

@*vh100 is defined here so main can flex-grow the remaining space in the window
This keeps the footer at the bottom of the screen for short content*@
<body class="box-col box-justify3 c-bg zero vh100">

    <header class="header-style w100 c-fg c-shadow">
        <nav class="max-w100">
            <div class="box-wraprow box-center3">
                <div class="box-row box-center3 header-title-box-media">

                    <a class="header-logo box-center0" asp-area="" asp-page="/Index">
                        <div class="box-row box-center0">
                            <span class="header-logo-utficon">💼</span>
                            <div class="box-col header-logo-font">
                                <span>Studio</span>
                                <span>Briefcase</span>
                            </div>
                        </div>

                        @*  <img src="~/images/internal/StudioBriefcaseBanner.png" alt="Site_Logo" class="m3" style="max-width:225px;"> *@
                    </a>
                    <div class="header-title-box-btn-media">
                        <button class="me-pushend theme-avatar event-toggle c-menu" data-target="layout-navbtn">
                            <span class="navbar-toggler-icon">M</span>
                        </button>
                    </div>
                </div>

                <div class="header-link-box-media box-row box-center3 me-grow1 center3" id="layout-navbtn">

                    <ul class="box-row zero mx20">
                        <li class="me-block">
                            <a class="theme-link text-lg" id="language-parameter" asp-area="" asp-page="/Library/Index">📚library</a>
                        </li>
                        <li class="me-block">
                            <details class="theme-link text-lg" style="position:relative">
                                <summary class="summary-icon-wrench event-toggle" data-target="layout-tools">Tools</summary>
                                <div class="box-col tools-content zero c-fg" id="layout-tools">
                                    <span class="text-center">Docy Drip</span>
                                    <hr class="w100" />
                                    <span class=""><a class="theme-link text-lg" asp-area="" asp-Page="/Tools/DocyDrip/TEO">📝TEO</a></span>
                                </div>
                            </details>
                        </li>
                        <li class="me-block">
                            <details class="theme-link text-lg" style="position:relative">
                                <summary class="summary-icon-about event-toggle" data-target="layout-support">Support</summary>
                                <div class="box-col tools-content zero c-fg" id="layout-support">
                                    <span class="zero"><a class="theme-link text-lg" asp-area="" asp-Page="/Connect/Index">🌐Connect</a></span>
                                    <span><a class="theme-link text-lg" asp-area="" asp-page="/Support/Index">🧻Support</a></span>
                                    <span><a class="theme-link text-lg" asp-area="" asp-page="/Support/History">⛽Blog</a></span>
                                </div>
                            </details>
                        </li>
                        <li class="me-block">
                            <details class="theme-link text-lg" style="position:relative">
                                <summary class="summary-icon-questionmark event-toggle" data-target="layout-about">About</summary>
                                <div class="box-col tools-content zero c-fg" id="layout-about">
                                    <span><a class="theme-link text-lg" asp-area="" asp-page="/About/Index">🧬Author Bio</a></span>
                                </div>
                            </details>
                        </li>


                        @*                         <li class="me-block">
                        <a class="theme-link text-lg" asp-area="" asp-page="/About/Index">about</a>
                        </li> *@
                        @*                         <li class="me-block">
                        <a class="theme-link text-lg" asp-area="" asp-page="/Support/Index">🙊support</a>
                        </li> *@
                    </ul>

                    <div class="box-col container-relative mx20">

                        <img class="icon-btn event-toggle icon-square-media me-justify zero c-offset" data-target="header-menu" src="~/images/External/Icons/github-mark.png" alt="Menu Icon" />
                        @*                         <button class="menu-btn event-toggle c-fg zero text-md" data-target="header-menu">
                        <img class="icon-square-media me-justify zero c-fg" src="~/images/External/Icons/github-mark.png" alt="Menu Icon" />
                        </button> *@
                        <div class="box-col me-absolute c-menu menu-window" id="header-menu">
                            @* <partial name="_menuPartial" /> *@
                            @await Component.InvokeAsync("Page_Menu");
                        </div>

                    </div>
                </div>

            </div>

        </nav>

    </header>


    @* <Main> Element is handled in subLayout because I believed letting a subLayout
    have control of main styles would simply implementing layout specific behaviors.    *@@*
    I'm might back track on this tucking the main element inside the sublayout.
    When I plug this site wide picture inside a picture. Its going to compete for space with the main element. *@


    @RenderBody() @* LeftSide *@


    <footer class="box-col w100 zero c-fg">
        <div class="footer-content">
            <div class="box-row box-center0 zero">
                <span><a asp-area="" asp-page="/Home/Privacy">Privacy~ </a></span>
                <p class="zero" xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="http://studiobriefcase.com">StudioBriefcase</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://github.com/TAReber/StudioBriefcase-Web-App">Tyler A Reber</a> is marked with <a href="http://creativecommons.org/publicdomain/zero/1.0?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC0 1.0<img alt="CreateiveCommon image" style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img alt="creative commons thing" style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/zero.svg?ref=chooser-v1"></a></p>
            </div>
        </div>

    </footer>


    <script src="~/scripts/site.js"></script>
    <script src="~/scripts/MainLayout.js"></script>
    <script src="~/scripts/ColorModes.js"></script>
    @*jquery Added for Ajax to fetch api data*@
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

StudioBriefcase/StudioBriefcase/Pages/Shared/_Layout_iFrame.cshtml
<!DOCTYPE html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @*Site Specific Styles and themes*@
    <link rel="stylesheet" href="~/css/site.css" />
    @*Globally Used Styles for element flow and control*@
    <link rel="stylesheet" href="~/css/baseStyles.css" />
    @* Redefinition of html Tags *@
    <link rel="stylesheet" href="~/css/themes.css" />
    @*Helper Styles to add visual Assistance to the development process*@
    <link rel="stylesheet" href="~/css/helperStyles.css" />

    @* Default Colors used in the website and altered values used in darkmode *@
    <partial name="_colors" />
    <link rel="stylesheet" href="~/css/ColorStyles.css" />

    @* <link rel="stylesheet" href="~/@(nameof(StudioBriefcase)).styles.css" /> *@

</head>

<body class="w100 box-col zero c-bg" style="height:100vh; overflow:hidden;">
    <main class="box-col" style="overflow-y:auto; overflow-x:hidden; ">
        @if(ViewData["Library"] != null)
        {
            @await Component.InvokeAsync("miniQuickLinks", new { libraryName = ViewData["Library"] })
            <div class="accordion-target-vertical" id="navigation-Parameters">
                <label class="text-sm w100" id="PageCategory" data-name="@ViewData["Category"]">@ViewData["Category"]</label>
                <label class="text-sm w100" id="PageLibrary" data-name="@ViewData["Library"]">@ViewData["Library"]</label>
                <label class="text-sm w100" id="PageSubject" data-name="@ViewData["Subject"]">@ViewData["Subject"]</label>
                <label class="text-sm w100" id="PageTopic" data-id="@ViewData["TopicID"]">@ViewData["Topic"]</label>

                
                @await Component.InvokeAsync("Page_Tags")
            </div>

        }
        <div class="box-row">
            <label class="text-sm w100" id="color_mode_toggle">Dark</label>
            <label class="p2">Language:</label>
            <select class="zero" name="Language" id="menu-language" onchange="UpdateLanguage()">
                <option value="1">English</option>
            </select>
        </div>

        <div class="p5">
            @RenderBody()
        </div>
        

        @* The location that is used to inject Post Inspection Form *@
        @* @if(User.Identity?.IsAuthenticated == true)
        { *@
        <div id="UserPostManagerLocation">
        </div>
        @* } *@

    </main>

</body>
    



<script src="~/scripts/site.js"></script>
<script src="~/scripts/ColorModes.js"></script>


<script src="~/scripts/LibraryFunctions.js"></script>
<script src="~/scripts/GlobalLibraryFunctions.js"></script>
<Script src="~/scripts/library/Vulkan.js"></Script>



@*jquery Added for Ajax to fetch api data*@
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
@RenderSection("Scripts", required: false)

StudioBriefcase/StudioBriefcase/Pages/Shared/_colors.cshtml
@* 
Color Management System - Episode 3
Realtime updates can occcur by changing the color values in the colorscheme style :root.

The color Management system also provides styles prefixed with a c for use in the html markup.
*@


<style id="colorscheme">
    :root {        
        --background: #eeeeee;
        --foreground: #cccccc;      
        --text-color1: #000000;
        --text-color2: #000000;
        --shadow1: #548BC0;
        --shadow2: #942E5A;
        --offset: #777777;
        --menu-background: #aaaaaa;
    }

/*     .c-bg {
        background-color: var(--background);
        color: var(--text-color1);
    }

    .c-fg {
        background-color: var(--foreground);
        color: var(--text-color2);
    }

    .c-shadow {
        box-shadow: 0 1px 3px 0 var(--shadow1), 0 2px 5px 0 var(--shadow2);
    }

    .c-menu {
        background-color: var(--menu-background);
        color: var(--text-color1);
    }


    .c-offset {
        background-color: var(--offset);
        color: var(--text-color1);
    }

        .c-offset.expanded {
            background-color: var(--menu-background);
            color: var(--text-color2);
        }

    a {
        text-decoration: none;
        color: var(--shadow1);
    }

        a:visited {
            color: var(--shadow2);
        }

        a:hover {
            color: var(--offset); /* #a1a1a1;*/
        }

 */
</style>

StudioBriefcase/StudioBriefcase/Pages/Shared/_footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<footer class="box-col w100 zero c-fg">
    <div class="footer-content">
        &copy; 2023 - Studio Briefcase - <a asp-area="" asp-page="/Home/Privacy">Privacy</a>
    </div>

</footer>

StudioBriefcase/StudioBriefcase/Pages/Shared/_miniPagePartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="box-row ">

    <div class="box-col mini-view c-fg" id="mini-picture">

        @* Database Control Block *@
        <div class="box-col w100 h100 c-shadow">
            <div class="box-row box-center3 m5 w75">
                <div class="box-col" id="mini-map">
                    Error: Getting Content from OnContentLoaded
                </div>
                <button onclick="RetrieveRazorPage()">
                    Go
                </button>
            </div>

            @* Mini-Page Content Displayed Here *@
@*              <div class="" id="mini-page">
                TODO: Load in Content Area
            </div>  *@
             <div class="mini-container zero c-bg"> 
                <iframe class="zero" id="mini-page" scrolling="no" src="/mini"></iframe>
                
             </div> 



        </div>
    </div>


</div>

StudioBriefcase/StudioBriefcase/Pages/Shared/_subLayout_Default.cshtml
@{
    Layout = "_Layout.cshtml";
    <link rel="stylesheet" href="~/@(nameof(StudioBriefcase)).styles.css" />
}

@* The main Element Represents the Entire Area between the Header and footer defined in the _Layout.cshtml *@
@* me-grow1 is what anchors the header and footer to the top and bottom of the page. *@
<main class="box-col me-grow1 w100 c-bg" style="overflow:hidden;">

    <div class="main-content box-row h100">
        <div class="box-row me-grow1 h100" style="overflow:auto">

            <div class="box-col me-grow1" style="margin: 2% 13%;">
                @RenderBody()
            </div>
            @* Button for MiniPagePartial *@
            <div class="h100 m2">
                <button class="mini-button event-toggle c-fg" data-target="mini-picture">|</button>
            </div>
        </div>

        @* MiniPagePartial id in here*@
         @* <partial name="_miniPagePartial" />  *@
         @await Component.InvokeAsync("Page_MiniFrame");


    </div>


    @*<partial name="_footer" />*@
</main>

StudioBriefcase/StudioBriefcase/Pages/Shared/_subLayout_Library.cshtml
@{
    Layout = "_Layout.cshtml";
    /*Style Sheet Uses ASP.NET feature called CSS Isolation. */
    <link rel="stylesheet" href="~/@(nameof(StudioBriefcase)).styles.css" />
     string? thisDirectory = System.IO.Path.GetDirectoryName(Context.Request.Path);
     // string[] folders = thisDirectory!.Split('\\');//Phased out, moved to BasePageModel
     // string Category = folders[folders.Length - 3];//Phased out, moved to BasePageModel
     // string library = folders[folders.Length - 2];//Phased out, moved to BasePageModel
     // string subject = folders[folders.Length - 1];//Phased Out, moved to BasePageModel
     // string topic = System.IO.Path.GetFileNameWithoutExtension(Context.Request.Path);
    
}

<head>
    @* <link rel="stylesheet" href="~/css/LibraryStyles/@(library).css" /> *@
    
</head>

<main class="box-row me-grow1 w100 c-bg" style="overflow:hidden">

    <div class="box-row h100">

        <div class="box-row c-fg expanded" id="sublayout-sidebar-navigator">
            <div class="sublayout-sidebar-scrollbar">
                <h6 class="sublayout-link-title">@ViewData["Library"]?.ToString() Links</h6>
                @{
                    /* Calls a function in ViewCoponents/LibraryLinkViewComponent.cs using dependency injection */
                }
                @await Component.InvokeAsync("PageQuickLinks", new { libraryName = ViewData["Library"] })
                @if (User.Identity?.IsAuthenticated == true && (String.Equals(User.FindFirst("privilege")?.Value, "Admin", StringComparison.OrdinalIgnoreCase) || String.Equals(User.FindFirst("privilege")?.Value, "Moderator", StringComparison.OrdinalIgnoreCase)))
                {
                    <button class="event-toggle w100" data-target="librarylinks-form">Update Links</button>
                }
                                
                @* Create a ViewComponent for Users Library Preferences here *@

               

                <span></span>
                <div class="accordion w100">
                    <div class="accordion-item w100">
                        <button class="event-toggle w100" data-target="navigation-Parameters">
                            Post Filter Settings
                        </button>
                        <div class="accordion-target-vertical" id="navigation-Parameters">
                            <label class="text-sm w100" id="PageCategory" data-name="@ViewData["Category"]">@ViewData["Category"]</label>
                            <label class="text-sm w100" id="PageLibrary" data-name="@ViewData["Library"]">@ViewData["Library"]</label>
                            <label class="text-sm w100" id="PageSubject" data-name="@ViewData["Subject"]">@ViewData["Subject"]</label>
                            <label class="text-sm w100" id="PageTopic" data-id="@ViewData["TopicID"]">@ViewData["Topic"]</label>
                            @await Component.InvokeAsync("Page_Tags")
                        </div>
                    </div>
                </div>
                
                <div class="p2"></div>
                @await Component.InvokeAsync("PageNavigation", new { topicID =  ViewData["TopicID"], languageID = ViewData["LanguageID"] })

                <div class="whitespace"></div>
            </div>
        </div>
        <div class="h100 m2">
            <button class="sublayout-sidebar-toggle c-fg event-toggle" data-target="sublayout-sidebar-navigator">I</button>
        </div>
    </div>

@*     <div class="box-row box-justify0 w100 h100" style="overflow:auto;">
        <div class="box-col box-w100-margin w75">
            @RenderBody()
        </div>

    </div> *@
    <div class="main-content box-row h100">
        <div class="box-row me-grow1 h100" style="overflow:auto">
            <div class="box-col me-grow1" style="margin: 2% 7%;">
                @RenderBody()
            </div>
            @* Button for MiniPagePartial *@
            <div class="h100 m2">
                <button class="mini-button event-toggle c-fg" data-target="mini-picture">|</button>
            </div>
        </div>


        @* MiniPagePartial id in here*@
        @* <partial name="_miniPagePartial" /> *@
        @await Component.InvokeAsync("Page_MiniFrame");
    </div>

</main>

@* Button that allows admins and moderators to update the quicklinks in the library sublayout *@
@if (User.Identity?.IsAuthenticated == true && (String.Equals(User.FindFirst("privilege")?.Value, "Admin", StringComparison.OrdinalIgnoreCase) || String.Equals(User.FindFirst("privilege")?.Value, "Moderator", StringComparison.OrdinalIgnoreCase)))
{
    <div class="form" id="librarylinks-form">
        <div class="form-content c-bg show">
            <div class="box-row">
                <button onclick="updateLibraryLinks()" id="updateLinksButton">Update Links</button>
                <button id="not implemented">cancel not implemented</button>
            </div>
            @await Component.InvokeAsync("PageQuickLinks", new { libraryName = ViewData["Library"], switchvalue = 1 }));
        </div>
        <div class="form-background event-toggle" data-target="librarylinks-form"></div>
    </div>
}

@* The location that is used to inject Post Inspection Form *@
@* @if(User.Identity?.IsAuthenticated == true)
{ *@
    <div id="UserPostManagerLocation">

    </div>
@* } *@


<script>
    // document.addEventListener('DOMContentLoaded', () => {
    //     ToggleExpanded('@ViewData["Subject"]?.ToString()');
    // });

    //A Function that creates a single string out of JSON Obejcts and Inserts the string into a database.
    function updateLibraryLinks(event) {
        //console.log("The javascript updateLibraryLinks function was called");
        //console.log("Custodian Quicklinks client function");
        let item = [];
        let inputFields = document.querySelectorAll(".link-input");
        let objects = [];

        inputFields.forEach((input) => {
            let propertyName = input.getAttribute('data-property');
            item.push(input.value);
        });

        for (let i = 0; i < 5; i++) {
            if (item[0 + (i * 3)] != "null" && item[0 + (i * 3)] != "null") {

                let object = {
                    SiteUrl: item[0 + (i * 3)],
                    ImgSource: item[1 + (i * 3)],
                    ShorthandDesc: item[2 + (i * 3)]
                }

                objects.push(object);
            }

        };

        //After Objects Created, I needed to create a model to store the string in and pass in the parameters.
        fetch('/api/custodianController/SetLibraryQuickLinks', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                LibraryName: "@ViewData["Library"]?.ToString()",
                JsonString: JSON.stringify(objects)
            })
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error("Network response was not ok");
                }
                return response.json();
            }).then(data => {
                console.log(data);
                //location.reload();
            }).catch(error => {
                console.error("Fetch Operation Failed to update library links in _subLayout_Library.cshtml", error);
            })
    }

</script>

@section Scripts {
    <script src="~/scripts/LibraryFunctions.js"></script>
    <script src="~/scripts/GlobalLibraryFunctions.js"></script>
    <Script src="~/scripts/library/Vulkan.js"></Script>
}