StudioBriefcase/StudioBriefcase/Models/BasePageModel.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StudioBriefcase.Services;
using System.Security.Principal;

namespace StudioBriefcase.Models
{
    /// <summary>
    /// BasePageModel is the base class for all Libraries in the StudioBriefcase application
    /// </summary>
    public class BasePageModel : PageModel
    {
        private PageService _pageService;
        //private uint _topicID;
        public PageDataMap datamap { get; set; }
        //public uint LanguageID { get; set; } = 0;


        public BasePageModel(PageService pageservice, uint topicID)
        {
            _pageService = pageservice;
            datamap = new PageDataMap(topicID);
            //_topicID = topicID;           
        }


        public async virtual Task<IActionResult?> OnGet(string language)
        {
            
            //uint langID = 0;
            if (language != null)
            {
                datamap._languageID = await _pageService.LanguagesIDexists(language);

                // If the language is not found, default to Master Language
                if (datamap._languageID == 0)
                {
                    string path = Request.Path.Value!;
                    string defaultPath = path.Replace($"/{language}", "");
                    return Redirect(defaultPath);
                }
            }

            CreateSubLayoutViewData();
     
            return Page();
        }

        private void CreateSubLayoutViewData()
        {
            bool iframe = Request.Query.TryGetValue("iframe", out var test);

            if (iframe)
            {
                ViewData["Layout"] = "/Pages/Shared/_Layout_iFrame.cshtml";
            }
            else
            {
                ViewData["Layout"] = "/Pages/Shared/_subLayout_Library.cshtml";
            }
            // Set Layout = ViewData["Layout"]?.ToString();

            //ViewData["iframe"] = iframe;

            var dbmap = Request.Path.Value!.Split('/').ToArray();
            ViewData["Category"] = dbmap![2];
            ViewData["Library"] = dbmap![3];
            ViewData["Subject"] = dbmap![4];
            ViewData["Topic"] = dbmap![5];
            //ViewData["Language"] = dbmap[6] ?? "Master";
            ViewData["LanguageID"] = datamap._languageID;
            ViewData["TopicID"] = datamap._topicID;
        }

        public async Task<IActionResult> OnPostUpdateSubjectAlias(string aliasName, uint mapid, uint langid)
        {
            datamap = new PageDataMap(mapid);
            datamap._languageID = langid;
            CreateSubLayoutViewData();

            await _pageService.UpdateMapAliasNameAsync("subjects", mapid, langid, aliasName);
            

            return Page();
        }

        public async Task<IActionResult> OnPostUpdateTopicAlias(string aliasName, uint mapid, uint langid)
        {
            datamap = new PageDataMap(mapid);
            datamap._languageID = langid;
            CreateSubLayoutViewData();

            await _pageService.UpdateMapAliasNameAsync("topics", mapid, langid, aliasName);

            return Page();
        }
    }

    public class PageDataMap
    {
        public uint _topicID { get; set; }
        public uint _languageID { get; set; }
        public PageDataMap(uint topicID)
        {
            _topicID = topicID;
        }
    }

    public class PageQuickLinksJSONModel
    {
        public string LibraryName { get; set; } = string.Empty;
        public string JsonString { get; set; } = string.Empty;
    }

    public class PageQuickLinksModel
    { 
        public string SiteUrl { get; set; } = string.Empty;
        public string ImgSource { get; set; } = string.Empty;
        public string ShorthandDesc { get; set; } = string.Empty;
    }

    public class UINTTypeModel
    {
        public uint uinttype { get; set; }
    }

    public class ID_String_Pair_Model
    {
        public uint id { get; set; }
        public string text { get; set; } = string.Empty;
    }

    public class ID_String_Alias_Pair_Model
    {
        public uint id { get; set; }
        public string text { get; set; } = string.Empty;
        public string alias { get; set; } = string.Empty;
    }

    /// <summary>
    /// Model used in the Index.cs pages, To be phased out for datadriven approach
    /// </summary>
    public class Map_Alias_Pair_Model
    {
        public ID_String_Pair_Model map { get; set; } = new ID_String_Pair_Model();
        public AliasNamesModel alias { get; set; } = new AliasNamesModel();

        public Map_Alias_Pair_Model() { 
            map = new ID_String_Pair_Model();
            alias = new AliasNamesModel();
        }

        public Map_Alias_Pair_Model(uint mapID, string mapName, string alias_name, string alias_description)
        { 
            map = new ID_String_Pair_Model { id = mapID, text = mapName };
            alias = new AliasNamesModel { name = alias_name, description = alias_description };
        }

        public Map_Alias_Pair_Model(ID_String_Pair_Model _map, AliasNamesModel _alias) {
            map = _map;
            alias = _alias;       
        }

    }

    public class AliasNamesModel
    {
        public string name { get; set; } = string.Empty;
        public string description { get; set; } = string.Empty;
    }

    public class SubjectTopicsAliasEditorModel
    {
        public uint mapID { get; set; }
        public uint languageID { get; set; }
        public string topicName { get; set; } = string.Empty;
        public string topicAlias { get; set; } = string.Empty;
        public string subjectName { get; set; } = string.Empty;
        public string subjectAlias { get; set; } = string.Empty;
    }

    //Phasing Out
    public class staticlibraryLinkModel
    {
        
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
    }

}

StudioBriefcase/StudioBriefcase/Pages/Shared/Components/Page/_PageQuickLinks.cshtml
@model List<StudioBriefcase.Models.PageQuickLinksModel>;
<!-- Styles Defined with CSS Isolation: Note - I didn't link the stylesheet, why do they work?' -->
<ul class="doc-list-style">
    @foreach (var document in Model)
    {
        <li>
            <div class="thumbnail-link w-fit">
                <a href="@(document.SiteUrl)" target="_blank">
                    <img src="@(document.ImgSource)" class="doc-logo" />
                </a>
                <div class="thumbnail-text">@(document.ShorthandDesc)</div>
            </div>
        </li>
    }
</ul>

StudioBriefcase/StudioBriefcase/Pages/Shared/Components/Page/_PageSection_Post.cshtml
@* 
StudioBriefcase/Pages/Shared/Components/Page/_PageSection_Post.cshtml
By: Tyler Andrew Reber

PageSections are intended to be reusuable containers for different types of content hosted in the database.
*@

@model int

<div class="accordion w100">

    <div class="accordion-item c-bg">

        <button class="accordion-toggle c-fg event-toggle" type="button" data-target="@Model">
            <h6>Section @Model</h6>
        </button>

        <div class="accordion-target-vertical box-col" id="@Model">

            @* todo: row of partial views called tabs *@
            <div class="box-col zero">
                <div class="box-wraprow box-center3">

                    <div class="box-row zero">

                        @* enter all tabs here *@
                        @* <button>Article</button> *@
                        <button data-type='video' data-section='@(Model)' onclick='VideoButtonTest(this)' id='videobuttontest'>Video</button>
                        @* <button>Stackoverflow</button> *@

                    </div>
                    <div class="box-row">
                        @*                         @if(User.Identity?.IsAuthenticated == true)
                        { *@
                        @*<label for="PostType">Post Type:</label>
                        <select name="sectionPostType@(Model.sectionlocation)" id="LinkType@(Model.sectionlocation)">
                        <partial name="\Components\Posts\_PostTypeOptions" />
                        </select> *@
                        <input type="text" class="text-sm" id="sectionInspectorInput@(Model)" value="TODO_POST_LINK" />
                        <button onclick="OpenPostDetailsForm(@(Model))">Inspect</button>
                        @*                         }
                        else
                        {
                        <span class="text-md">Login to Add Post</span>
                        } *@

                    </div>

                </div>
                <div class="box-col w100 zero section-viewport" id="viewport@(Model)" loading="lazy">
                </div>

            </div>

        </div>
    </div>
</div>

StudioBriefcase/StudioBriefcase/Pages/Shared/Components/Page/_Page_Content_BasicSegment.cshtml
@{
}
@model uint 


<div class="teo-mastercontainer zero" id="EditableSegement@(Model)">

    <div class="box-col w100 box-center3 zero">
        <div class="box-row w100">
            <span class="zero text-lg w100" id="EditorHeader" contenteditable="false"><b>@(Model) Fancy Description Title </b></span>
            <details >
                <summary class="summary-icon-book event-docydrip-teo" data-target="EditableSegement@(Model)"></summary>
            </details>
        </div>

        <div class="box-wraprow box-center0 teo-button-container" id="EditorButtons">

            <!-- Text Undo/Redo-->
@*          <button class="Editor-btn" id="undo"><b>&#8630</b></button>
            <button class="Editor-btn" id="redo"><b>&#8631</b></button>
            
            <!-- Special Formatting -->
            <button class="Editor-btn" id="link"><b>&#9939</b></button>
            <button class="Editor-btn" id="unlink" style="text-decoration:line-through"><b>&#9939</b></button>

            <select class="Editor-select" id="typeface"></select>
            <select class="Editor-select" id="font-size"></select>
                    
            <button class="Editor-btn" id="copy">C</button>
            <details><summary class="icon-save"></summary></details> *@
        </div>

    </div>

    <div class="teo-editorbody" id="docydrip-teo-body" contenteditable="false">

    </div>

    <div class="w100" id="EditorFooter">
        <span>Edited by: Tyler Reber</span>
    </div>

</div>

StudioBriefcase/StudioBriefcase/Pages/Shared/Components/Page/_Page_Content_Websites.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<StudioBriefcase.Models.ID_String_Alias_Pair_Model>;

    

StudioBriefcase/StudioBriefcase/Pages/Shared/Components/Page/_Page_LanguageSelect.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model StudioBriefcase.Models.LanguageModel

<label class="p2" for="menu-language">Language:</label>
<select class="zero" id="menu-language" onchange="UpdateLanguage()">
    @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.options, Model.selectedID))
</select>

StudioBriefcase/StudioBriefcase/Pages/Shared/Components/Page/_Page_Menu.cshtml
@*
    Episode 3 - Color Management System, Realtime Color Updates
*@
@using StudioBriefcase.Models;
@model StudioBriefcase.Models.LanguageModel
@{

}

<ul class="box-col box-center3 menu-style p3">
    <li class="box-row box-center3 w100">
        <span class="text-sm" style="color:inherit">Color Mode</span>
        <button class="menu-btn menu-btn-size c-fg" onclick="toggleColorScheme(this)" id="color_mode_toggle" data-target="colorscheme">Light</button>
    </li>
    <li class="box-col box-center3 w100">
        @* button class="menu-btn menu-btn-link c-fg" onclick="OpenSettingsPage()"><span class="text-sm" style="color:inherit">Settings</span></button> *@
        <button class="menu-btn menu-btn-link event-toggle c-fg" data-target="user-form"><span class="text-sm" style="color:inherit">Settings</span></button>
    </li>
    <li class="box-row">
        <label class="p2" for="menu-language">Language:</label>
        <select class="zero" id="menu-language" onchange="UpdateLanguage()">
            <option value="0">Master</option>
            @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.options, (uint)0))
        </select>
    </li>
    @if (User.Identity?.IsAuthenticated == true)
    {
        <li class="box-col box-center3 w100">
            <span class="text-sm" style="color:inherit">@User.FindFirst("role")?.Value</span>
            <span class="text-sm" style="color:inherit">@User.FindFirst("name")?.Value</span>
            @* Dynamic Redirect returnUrl Episode 2 *@
            <a class="menu-btn menu-btn-link text-center w100 c-fg" href="/logout?returnUrl=@Context.Request.Path">Logout</a>
        </li>
    }
    else
    {
        <li class="box-col box-center0 w100">
            <span class="text-sm" style="color:inherit">GitHub OAuth</span>
            @* Dynamic Redirect returnUrl Episode 2 *@
            <a class="menu-btn menu-btn-link text-center w100 c-fg" href="/login?returnUrl=@Context.Request.Path">Login</a>
        </li>
    }
</ul>


<div class="form c-bg" id="user-form">
    <div class="form-content c-fg c-shadow">
        <h5 class="text-center w100 c-fg">User Menu</h5>
        <div class="accordion w100">
            <div class="accordion-item">

                <button class="accordion-toggle c-fg event-toggle text-sm" data-target="menu-color-picker">
                    Advanced Color Mode Panel
                </button>

                <div class="accordion-target-vertical box-col c-fg" id="menu-color-picker">
                    <div class="box-row box-center2">
                        <button class="menu-btn w75 c-fg" onclick="SaveCustomColorScheme()" data-target="colorscheme">Save Colors</button>
                        <button class="menu-btn w75 c-fg" onclick="ClearCustomColorLocalStorage()" data-target="colorscheme">Clear Cache</button>
                    </div>
                    <div id="color_picker_list">
                        <div class="box-row box-center2">
                            <span class="text-sm" style="color:inherit">Background</span>
                            <input type="color" id="color_background" name="--background" value="#eeeeee" oninput="ApplyColor(this)" />
                        </div>
                        <div class="box-row box-center2">
                            <span class="text-sm" style="color:inherit">Foreground</span>
                            <input type="color" id="color_foreground" name="--foreground" value="#cccccc" oninput="ApplyColor(this)" />
                        </div>
                        <div class="box-row box-center2">
                            <span class="text-sm" style="color:inherit">Text Color 1</span>
                            <input type="color" id="color_text-color1" name="--text-color1" value="#000000" oninput="ApplyColor(this)" />
                        </div>
                        <div class="box-row box-center2">
                            <span class="text-sm" style="color:inherit">Text Color 2</span>
                            <input type="color" id="color_text-color2" name="--text-color2" value="#000000" oninput="ApplyColor(this)" />
                        </div>
                        <div class="box-row box-center2">
                            <span class="text-sm" style="color:inherit">Shadow 1</span>
                            <input type="color" id="color_shadow1" name="--shadow1" value="#000000" oninput="ApplyColor(this)" />
                        </div>
                        <div class="box-row box-center2">
                            <span class="text-sm" style="color:inherit">Shadow 2</span>
                            <input type="color" id="color_shadow2" name="--shadow2" value="#cccccc" oninput="ApplyColor(this)" />
                        </div>
                        <div class="box-row box-center2">
                            <span class="text-sm" style="color:inherit">Offset</span>
                            <input type="color" id="color_offset" name="--offset" value="#cccccc" onInput="ApplyColor(this)" />
                        </div>
                        <div class="box-row box-center2">
                            <span class="text-sm" style="color:inherit">Menu Background</span>
                            <input type="color" id="color_menu_background" name="--menu-background" value="#111111" onInput="ApplyColor(this)" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @if (User.Identity?.IsAuthenticated == true)
        {
            <div class="box-col">
                <span>@User.FindFirst("name")</span>
                <span>@User.FindFirst("privilege")</span>
                <a class="icon-btn" href="@User.FindFirst("webpage")?.Value" target="_blank">
                    <img class="icon-square-media" src="@User.FindFirst("picture")?.Value" alt="Github profile Pic" />
                </a>
                <span>@User.FindFirst("class")</span>

            </div>

            <select id="Menu_RoleDropdown">
                <option value="Private">Private</option>
                <option value="Student">Student</option>
                <option value="Teacher">Teacher</option>
                <option value="Educator">Educator</option>
                <option value="Professional">Professional</option>
                <option value="Researcher">Researcher</option>
                <option value="Content Creator">Content Creator</option>
            </select>

            <button class="" type="button" onclick="updateUserRole(event)"><span class="text-sm" style="color:inherit">Apply</span></button>
        }

    </div>
    <div class="form-background event-toggle" data-target="user-form" />

</div>

StudioBriefcase/StudioBriefcase/Pages/Shared/Components/Page/_Page_MiniFrame.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model StudioBriefcase.Models.MiniViewDataModel;

<div class="box-row ">

    <div class="box-col mini-view c-fg" id="mini-picture">

        @* Database Control Block *@
        <div class="box-col w100 h100 c-shadow">
            <div class="box-row box-center3 m5 w75">
                <div class="box-col" id="mini-map">
                    Error: Getting Content from OnContentLoaded
                </div>
                <select class="zero" id="mini-language">
                    <option value="0">Master</option>
                     @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.languages, (uint)0)) 
                </select>
                <button onclick="RetrieveRazorPage()">
                    Go
                </button>
            </div>

            @* Mini-Page Content Displayed Here *@
            @*              <div class="" id="mini-page">
            TODO: Load in Content Area
            </div>  *@
            <div class="mini-container zero c-bg">
                <iframe class="zero" id="mini-page" scrolling="no" src=""></iframe>

            </div>



        </div>
    </div>


</div>

StudioBriefcase/StudioBriefcase/Pages/Shared/Components/Page/_Page_MiniSelects.cshtml
@*
    //Map Selectors in the Mini Layout
*@
@{
}
@model StudioBriefcase.Models.LibraryMapModel

<div class="box-row w100">
    <select style="width:150px;" type="text" id="mini-category" value=@Model.ids.CategoryID onchange="MapOptionsChangedDuplicate('mini',0)">
        @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.lists.Categories, Model.ids.CategoryID))
    </select>

    <select style="width:150px;" type="text" id="mini-library" value="@Model.ids.LibraryID" onchange="MapOptionsChangedDuplicate('mini',1)">
        @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.lists.Libraries, Model.ids.LibraryID))
    </select>
</div>

<div class="box-row w100">
    <select style="width:150px;" type="text" id="mini-subject" value="@Model.ids.SubjectID" onchange="MapOptionsChangedDuplicate('mini',2)">
        @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.lists.Subjects, Model.ids.SubjectID))
    </select>

    <select style="width:150px;" type="text" id="mini-topic" value="@Model.ids.TopicID">
        @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.lists.Topics, Model.ids.TopicID))
    </select>
</div>

StudioBriefcase/StudioBriefcase/Pages/Shared/Components/Page/_Page_NavigationLinks.cshtml
@*
    _subLayout_Library component used to create links in the navigation bar.

    Created for StudioBriefcase by:  Tyler Andrew Reber
*@

@* @model List<StudioBriefcase.Models.SubjectModel>; *@
@model StudioBriefcase.Models.SubLayoutNavigationModel;

@if(Model.languageID != 0)
{
     <details class="">
        <summary class="summary-icon-book"></summary>
        <form method="post" asp-page-handler="UpdateSubjectAlias">
            <label>@(Model.subject?.text)</label>
            <input type="text" name="aliasname" value="@(Model.subject?.alias)" autocomplete="off" placeholder="@(Model.subject?.text)">
            <input type="text" name="mapid" value="@(Model.subject?.id)" readonly hidden>
            <input type="text" name="langid" value="@Model.languageID" readonly hidden>
            <input type="submit" value="Save">
        </form>
        <form method="post" asp-page-handler="UpdateTopicAlias">
            <label>@(Model.topic?.text)</label>
            <input type="text" name="aliasname" value="@(Model.topic?.alias)" autocomplete="off" placeholder="@(Model.topic?.text)">          
            <input type="text" name="mapid" value="@(Model.topic?.id)" readonly hidden>
            <input type="text" name="langid" value="@Model.languageID" readonly hidden>
            <input type="submit" value="Save">
        </form>
    </details> 
}

<ul class="navigation-subject-list">

    @foreach (var subject in Model.Links)
    {
        <li>
            <div>
                <button class="navigation-toggle-btn" type="button" onclick="ToggleExpanded('@(subject.Name)')">
                    @(subject.Name)
                </button>
                <div class="navigation-topics-container" id="@(subject.Name)">
                    <ul class="navigation-topic-list">
                        @foreach (var topic in subject.Topics)
                        {
                            <li><a class="navigation-topic-style" id="language-parameter" asp-page="@(topic.PathUrl)">@(topic.Name)</a></li>
                        }


                    </ul>
                </div>
            </div>
        </li>
    }
</ul>

StudioBriefcase/StudioBriefcase/Pages/Shared/Components/Page/_Page_Navigation_Tags.cshtml
@* NOTE:
    This partial is Dynamically loaded and used in mutliple areas.
    SubmissionForms with 0 are the navigator.

    DEVELOPMENT TASK
        -The Tuple used in the partial Async can Defaults to 0, but can be used to load user saved values.
*@

@model StudioBriefcase.Models.TagsModel

<div class="box-row box-center2">
    <div class="box-col">
        <label for="PostType">OS:</label>
        <select name="OS" id="PageTag-OS">
            <option value="0">Any OS</option>
            @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.TagLists.Tags_OS, Model.ids.OS))
        </select>
    </div>

    <div class="box-col">
        <label for="PostType">IDE</label>
        <select name="OS" id="PageTag-IDE">
            <option value="0">Any IDE</option>
            @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.TagLists.Tags_IDE, Model.ids.IDE))
        </select>
    </div>
</div>

<div class="box-row box-center2">
    <div class="box-col" style="width:30%;">
        <label for="Tag1">Tag 1</label>
        <select name="Tag1" id="PageTag-1">
            <option value="0">Any</option>
            @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.TagLists.Tags_normal, Model.ids.Tag1)) 
        </select>
    </div>
    <div class="box-col" style="width:30%;">
        <label for="Tag2">Tag 2</label>
        <select name="Tag1" id="PageTag-2">
            <option value="0">Any</option>
            @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.TagLists.Tags_normal, Model.ids.Tag2))
        </select>
    </div>
    <div class="box-col" style="width:30%;">
        <label for="Tag1">Tag 3</label>
        <select name="Tag3" id="PageTag-3">
            <option value="0">Any</option>
            @await Html.PartialAsync("/Pages/Shared/Components/Base/_SelectOptions.cshtml", Tuple.Create(Model.TagLists.Tags_normal, Model.ids.Tag3))
        </select>
    </div>
</div>